# file: roles/scripts/tasks/main.yml
- name: Create scripts directory if missing | file
  ansible.builtin.file:
    path: '{{ lookup("env", "HOME") }}/.local/scripts'
    recurse: true
    state: directory
    mode: '0755'

- name: Link tmux_sessionizer | file
  ansible.builtin.file:
    src: '{{ playbook_dir }}/roles/scripts/files/tmux_sessionizer.link'
    dest: '{{ lookup("env", "HOME") }}/.local/scripts/tmux_sessionizer'
    state: link
    force: yes
