# file: roles/hyprland/tasks/main.yml

- name: Install Hyprland and Wayland ecosystem packages
  become: true
  ansible.builtin.pacman:
    name:
      - hyprland
      - hyprlock
      - hyprpaper
      - hypridle
      - xdg-desktop-portal-hyprland
      - wl-clipboard
      - dunst
      - rofi
      - playerctl
      - brightnessctl
      - network-manager-applet
      - wofi
    state: present

- name: Install Hyprshot
  block:
    - name: Clone/Update Hyprshot
      ansible.builtin.git:
        repo: "https://github.com/Gustash/Hyprshot"
        dest: '{{ lookup("env", "HOME") }}/.hyprland/Hyprshot'
        depth: 1
        version: "main"
        force: true
      register: hyprshot
      changed_when: true

    - name: Link Hyprshot to local bin
      ansible.builtin.file:
        src: '{{ lookup("env", "HOME") }}/.hyprland/Hyprshot/hyprshot'
        dest: '{{ lookup("env", "HOME") }}/.local/bin/hyprshot'
        state: link
        force: true

- name: Ensure backgrounds directory exists
  ansible.builtin.file:
    path: '{{ lookup("env", "HOME") }}/.local/share/backgrounds'
    state: directory
    mode: "0755"

- name: Link left background
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/i3wm/files/Space_expanded.png"
    dest: '{{ lookup("env", "HOME") }}/.local/share/backgrounds/Space_expanded.png'
    state: link
    force: true

- name: Link right background
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/i3wm/files/Stellar_expanded.png"
    dest: '{{ lookup("env", "HOME") }}/.local/share/backgrounds/Stellar_expanded.png'
    state: link
    force: true

- name: Create Hyprland config directory
  ansible.builtin.file:
    path: '{{ lookup("env", "HOME") }}/.config/hypr'
    state: directory
    mode: "0755"

- name: Link hyprland.conf
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/hyprland/files/hyprland.conf.link"
    dest: '{{ lookup("env", "HOME") }}/.config/hypr/hyprland.conf'
    state: link
    force: true

- name: Copy hyprland custom config (only if not already present)
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/hyprland/files/custom.conf"
    dest: '{{ lookup("env", "HOME") }}/.config/hypr/custom.conf'
    mode: "0644"
    force: false

- name: Link hyprpaper.conf
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/hyprland/files/hyprpaper.conf.link"
    dest: '{{ lookup("env", "HOME") }}/.config/hypr/hyprpaper.conf'
    state: link
    force: true
