# file: roles/hyprland/tasks/main.yml

- name: Install Hyprland and Wayland ecosystem packages
  become: true
  ansible.builtin.package:
    name:
      - hyprland
      - hyprpaper
      - hyprlauncher
      - hypridle
      - hyprlock
      - xdg-desktop-portal-hyprland
      - hyprland-qt-support
      - hyprshot
      - hyprshutdown
      - polkit-kde-agent
      - waybar
      - wl-clipboard
      - swaync
      - rofi
      - playerctl
      - brightnessctl
      - network-manager-applet
      - archlinux-xdg-menu
      - gnome-calculator
      - qt6ct
      - cmake
      - ninja
      - git
      - base-devel
      - noto-fonts-emoji
      - adw-gtk-theme
      - thunar
      - thunar-archive-plugin #thunar-plugin
      - thunar-media-tags-plugin #thunar-plugin
      - thunar-shares-plugin #thunar-plugin
      - thunar-volman #thunar-plugin
      - gvfs #thunar-plugin
      - gvfs-mtp #thunar-plugin
      - sshfs #thunar-plugin
      - tumbler #thunar-plugin
      - ffmpegthumbnailer #thunar-plugin
      - syncthing
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Ensure backgrounds directory exists
  ansible.builtin.file:
    path: '{{ lookup("env", "HOME") }}/.local/share/backgrounds'
    state: directory
    mode: "0755"

- name: Link multiple config files
  file:
    src: "{{ playbook_dir }}/roles/hyprland/files/wallpapers/{{ item.src }}"
    dest: '{{ lookup("env", "HOME") }}/.local/share/backgrounds/{{ item.dest }}'
    state: link
    force: yes
  loop:
    - { src: "Space_expanded.png", dest: "Space_expanded.png" }
    - { src: "Stellar_expanded.png", dest: "Stellar_expanded.png" }

- name: Create Hyprland config directory
  ansible.builtin.file:
    path: '{{ lookup("env", "HOME") }}/.config/hypr'
    state: directory
    mode: "0755"

- name: Link hyprland.lua
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/hyprland/files/hyprland/hyprland.lua.link"
    dest: '{{ lookup("env", "HOME") }}/.config/hypr/hyprland.lua'
    state: link
    force: true

- name: Link hyprlock.conf
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/hyprland/files/hyprlock/hyprlock.conf.link"
    dest: '{{ lookup("env", "HOME") }}/.config/hypr/hyprlock.conf'
    state: link
    force: true

- name: Check for script folder | stat
  stat:
    path: "{{ lookup('env', 'HOME') }}/.config/hypr/scripts"
  register: scripts_stat

- name: Create scripts directory if missing | folder
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/hypr/scripts"
    recurse: true
    state: directory
    mode: "0755"
  when: not scripts_stat.stat.exists

- name: Link powermenu.sh
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/hyprland/files/hyprland/scripts/powermenu.sh.link"
    dest: '{{ lookup("env", "HOME") }}/.config/hypr/scripts/powermenu.sh'
    state: link
    force: true

- name: Copy hyprland custom config (lua, only if not already present)
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/hyprland/files/hyprland/custom.lua"
    dest: '{{ lookup("env", "HOME") }}/.config/hypr/custom.lua'
    mode: "0644"
    force: false

- name: Link hyprpaper.conf
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/hyprland/files/hyprpaper/hyprpaper.conf.link"
    dest: '{{ lookup("env", "HOME") }}/.config/hypr/hyprpaper.conf'
    state: link
    force: true

- name: Check if yay folder exists | stat
  stat:
    path: "{{ lookup('env', 'HOME') }}/stuff/yay.git"
  register: yay_stat

- name: Install yay
  block:
    - name: Clone yay
      shell: "git clone https://aur.archlinux.org/yay.git"
      args:
        chdir: '{{ lookup("env", "HOME") }}/stuff'
      when: not scripts_stat.stat.exists

    - name: Install yay
      command:
        argv:
          - "makepkg"
          - "-si"
        chdir: '{{ lookup("env", "HOME") }}/stuff/yay'
      when: not scripts_stat.stat.exists

    - name: first time config
      shell: "yay -Y --gendb && yay -Syu --devel && yay -Y --devel --save"
      args:
        chdir: '{{ lookup("env", "HOME") }}/stuff/yay'
      when: not scripts_stat.stat.exists
