# file: dotfiles.yml
- name: Set up Alexander's Environment
  hosts: local
  roles:
    - role: requirements
      tags:
        - requirements
    - role: hyprland
      tags:
        - hyprland
    - role: waybar
      tags:
        - waybar
    - role: scripts
      tags:
        - scripts
    - role: kitty
      tags:
        - kitty
    - role: zsh
      tags:
        - zsh
    - role: tmux
      tags:
        - tmux
    - role: neovim
      tags:
        - neovim
