# Custom configuration
# Run xrandr and configure this file after how this system is connected

# Set correct monitor placement
exec --no-startup-id xrandr --output DP-2 --primary --right-of DP-4

# Gaps between windows
gaps inner 5px

workspace $ws1 output DP-4
workspace $ws2 output DP-4
workspace $ws3 output DP-2
workspace $ws4 output DP-2
