# file: roles/requirements/tasks/main.yml
- name: Install Work requirements
  become: true
  ansible.builtin.package:
    name:
      - clang
      - cmake
      - curl
      - gcc
      - git
      - python
      - python-pip
      - nodejs
      - zip
      - unzip
      - copyq
      - eza
      - less
      - rsync
      - wl-clipboard
    state: present
