# file: roles/requirements/tasks/main.yml
- name: Install Work requirements
  become: true
  ansible.builtin.package:
    name:
      - clang
      - cmake
      - copyq
      - curl
      - eza
      - gcc
      - git
      - gnome-keyring
      - less
      - noto-fonts-emoji
      - python
      - python-pip
      - qt6ct
      - rsync
      - seahorse
      - unzip
      - nodejs
      - wl-clipboard
    state: present
